before_script:
  - apt-get update -qq && apt-get upgrade -qq
  - git clone https://github.com/ashinn/chibi-scheme
  - cd chibi-scheme && make && make install && cd ..

check:
  script:
    - make check
