# Site settings
title: Rapid Scheme
email: marc@rapid-scheme.org
description: Rapid Scheme is an implementation of the Scheme programming language supporting the R7RS
baseurl: ""
url: "https://www.rapid-scheme.org"

# Build settings
markdown: kramdown
